apiVersion: v1
kind: Service
metadata:
  labels:
    app: k8sexamimgdeploy
  name: k8sexamservice
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: k8sexamimgdeploy
